curd_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('curd_manage.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curd_manage/models.py
import os
import uuid
from django.db import models


class CommonModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    delete_at = models.DateTimeField(null=True)

    class Meta:
        abstract = True


class Position(CommonModel):
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'position'

    def __str__(self):
        return self.name


def upload_avatar(instance, filename):
    extension = os.path.splitext(filename)[1]
    avatar_path = 'avatar/'
    format_pattern = '{}-{}' + extension
    return avatar_path + format_pattern.format(uuid.uuid4(), uuid.uuid4())


class Employee(CommonModel):
    SEX_CHOICES = (
        (1, 'Male'),
        (2, 'Female')
    )

    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    avatar = models.ImageField(upload_to=upload_avatar)
    address = models.TextField()
    sex = models.IntegerField(default=1, choices=SEX_CHOICES)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    class Meta:
        db_table = 'employees'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">
	{% block style %}{% endblock %}
</head>
<body>
	{% block content %}{% endblock %}

	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block script %}{% endblock %}
</body>
</html>

templates/edit-employee.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
	<div style="width: 900px; margin: 0 auto">
		<h2 class="text-center py-5">Edit Employee</h2>
        <form method="post" action="{% url 'employee' employee_id=employee_id %}" enctype="multipart/form-data">
            {% if avatar %}
                <center><img src="{{ avatar.url }}" width="300" class="py-3" onerror="this.src='{% static 'images/avatar_blank.jpg' %}'"></center>
            {% else %}
                <center><img src="{% static 'images/avatar_blank.jpg' %}" width="300" class="py-3"></center>
            {% endif %}
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success">{{ message }}</div>
                        {% endif %}

                        {% if message.extra_tags == 'employee_form_error' %}
                            <div class="alert alert-danger">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}

            {% csrf_token %}
            <input type="hidden" name="_method" value="put">
            <div class="form-group">
                {{ employee_form.name }}
            </div>

            <div class="form-group">
                {{ employee_form.email }}
            </div>

            <div class="form-group">
                {{ employee_form.avatar }}
            </div>

            <div class="form-group">
                {{ employee_form.address }}
            </div>

            <div class="form-group">
                {{ employee_form.sex }}
            </div>

            <div class="form-group">

                {{ employee_form.positions }}
            </div>
            <div class="form-group">
                <button class="btn btn-success">Submit</button>
            </div>
        </form>
	</div>
{% endblock %}

{% block script %}{% endblock %}

templates/edit-position.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
	<div style="width: 900px; margin: 0 auto">
		<h2 class="text-center py-5">Edit Position</h2>
        <form method="post" action="{% url 'position' position_id=position_id %}">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success">{{ message }}</div>
                        {% endif %}

                        {% if message.extra_tags == 'position_form_error' %}
                            <div class="alert alert-danger">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}

            {% csrf_token %}
            <input type="hidden" name="_method" value="put">
            <div class="form-group">
                {{ position_form.name }}
            </div>

            <div class="form-group">
                <button class="btn btn-success">Submit</button>
            </div>
        </form>
	</div>
{% endblock %}

{% block script %}{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block style %}
	
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<h2 class="text-center py-5">Employees CURD</h2>
		{% if messages %}
		<div class="messages">
			{% for message in messages %}
				{% if message.tags == 'success' %}
					<div class="alert alert-{{ message.tags }}">{{ message }}</div>
				{% endif %}
			{% endfor %}
		</div>
		{% endif %}
		<div class="row">
			<div class="col-4">
				<form method="post" action="{% url 'positions' %}">
					<h4 class="text-center py-3">Insert Position</h4>
					{% if messages %}
						<div class="messages">
							{% for message in messages %}
								{% if message.extra_tags == 'position_form_error' %}
									<div class="alert alert-danger">{{ message }}</div>
								{% endif %}
							{% endfor %}
						</div>
					{% endif %}

					{% csrf_token %}
					<div class="form-group">
						{{ position_form.name }}
					</div>

					<div class="form-group">
						<button class="btn btn-success">Submit</button>
					</div>
				</form>

				{% if employee_form %}
				<form method="post" action="{% url 'employees' %}" enctype="multipart/form-data">
					<h4 class="text-center py-3">Insert Employees</h4>
					{% if messages %}
						<div class="messages">
							{% for message in messages %}
								{% if message.extra_tags == 'employee_form_error' %}
									<div class="alert alert-danger">{{ message }}</div>
								{% endif %}
							{% endfor %}
						</div>
					{% endif %}

					{% csrf_token %}
					<div class="form-group">
						{{ employee_form.name }}
					</div>

					<div class="form-group">
						{{ employee_form.email }}
					</div>

					<div class="form-group">
						{{ employee_form.avatar }}
					</div>

					<div class="form-group">
						{{ employee_form.address }}
					</div>

					<div class="form-group">
						{{ employee_form.sex }}
					</div>

					<div class="form-group">

						{{ employee_form.positions }}
					</div>
					<div class="form-group">
						<button class="btn btn-success">Submit</button>
					</div>
				</form>
				{% endif %}
			</div>

			<div class="col-8">
				<h4 class="text-center py-3">List</h4>
				<ul class="nav nav-tabs">
					<li class="nav-item">
					  <a class="nav-link active" data-toggle="tab" href="#menu1">Employees</a>
					</li>
					<li class="nav-item">
					  <a class="nav-link" data-toggle="tab" href="#menu2">Positions</a>
					</li>
				</ul>

				<div class="tab-content">
					<div id="menu1" class="container tab-pane active"><br>
						<table class="table table-striped">
							<thead>
							  	<tr>
									<th>Avatar</th>
									<th>Name</th>
									<th>Email</th>
									<th>Address</th>
									<th>Sex</th>
									<th>Position</th>
									<th>Action</th>
							  	</tr>
							</thead>
							<tbody>
								{% for employee in employees %}
								<tr>
									<td>
										{% if employee.avatar %}
											<img src="{{ employee.avatar.url }}" width="100" onerror="this.src='{% static 'images/avatar_blank.jpg' %}'">
										{% else %}
											<img src="{% static 'images/avatar_blank.jpg' %}" width="100">
										{% endif %}
									</td>
									<td>{{ employee.full_name }}</td>
									<td>{{ employee.email }}</td>
									<td>{{ employee.address }}</td>
									<td>{{ employee.get_sex_display }}</td>
									<td>{{ employee.position }}</td>
									<td>
										<a href="{% url 'employee' employee_id=employee.id %}" class="btn btn-info">Edit</a>
										<form method="post" action="{% url 'employees' %}" class="d-inline-block">
											{% csrf_token %}
											<input type="hidden" name="_method" value="delete">
											<input type="hidden" name="employee_id" value="{{ employee.id }}"/>
											<button class="btn btn-danger" type="submit">Delete</button>
										</form>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div id="menu2" class="container tab-pane fade"><br>
						<table class="table table-striped">
							<thead>
							  	<tr>
									<th>Name</th>
									<th>Action</th>
							  	</tr>
							</thead>
							<tbody>
								{% for position in positions %}
								<tr>
									<td>{{ position.name }}</td>
									<td>
										<a href="{% url 'position' position_id=position.id %}" class="btn btn-info">Edit</a>
										<form method="post" action="{% url 'positions' %}" class="d-inline-block">
											{% csrf_token %}
											<input type="hidden" name="_method" value="delete">
											<input type="hidden" name="position_id" value="{{ position.id }}"/>
											<button class="btn btn-danger" type="submit">Delete</button>
										</form>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block script %}{% endblock %}